### ISSUE TITLE
FakeData.getAttributeData(...) fills dateTime attributes as strings

### ISSUE THREAD

**Issue by jvanhill** [suvera/scim2-compliance-test-utility#10]
The switch block in `getAttributeData(...)` uses the wrong case (`datetime`) instead of `dateTime`. This results in a String (default case) being used for `dateTime` attributes instead of a well-formatted `dateTime`.

See [Table 1 in RFC 7643 Section 2.3](https://datatracker.ietf.org/doc/html/rfc7643#section-2.3).

**Comment by suvera** [comment]
fixed https://github.com/suvera/scim2-compliance-test-utility/commit/169a87ca80586f86866a6a4116108905a81f88e2
