### ISSUE TITLE
BUILD FAILURES

### ISSUE THREAD

**Issue by vitvitvit** [suvera/scim2-compliance-test-utility#2]
Hi,
I'm doing "Installation" steps to try this tool.
Unfortunately, I'm getting Build failure when doing _mvn clean install_:
`
[ERROR] Failed to execute goal on project scim2-compliance-test-utility: Could not resolve dependencies for project dev.suvera.opensource:scim2-compliance-test-utility:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.wso2.scim2:scim2-client:jar:1.0.1-SNAPSHOT -> org.wso2.charon:org.wso2.charon3.core:jar:3.0.0: Failed to read artifact descriptor for org.wso2.charon:org.wso2.charon3.core:jar:3.0.0: Could not transfer artifact org.wso2.charon:org.wso2.charon3.core:pom:3.0.0 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [wso2-nexus (http://maven.wso2.org/nexus/content/groups/wso2-public/, default, releases+snapshots), wso2.releases (http://maven.wso2.org/nexus/content/repositories/releases/, default, releases+snapshots), wso2.snapshots (http://maven.wso2.org/nexus/content/repositories/snapshots/, default, snapshots)] -> [Help 1]
`

Turns out that I need to copy settings file into .m2 folder (thanks for dockerfile where I've found this), after that this error is gone.

But another error occurs:
`
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project scim2-compliance-test-utility: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x8636cf4) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x8636cf4 -> [Help 1]
`

This is fixed by this suggestion:
https://stackoverflow.com/questions/66801256/java-lang-illegalaccesserror-class-lombok-javac-apt-lombokprocessor-cannot-acce

please fix these two issues, not to do these manual not obvious steps

**Comment by ramanarayana-narmala-securiti-ai** [comment]
fixed the issues in latest code.
