### ISSUE TITLE
User name attribute is not complex

### ISSUE THREAD

**Issue by gamma** [suvera/scim2-compliance-test-utility#9]
The following user creation request now fails:

    POST
    
    {
      "emails" : [ {
        "value" : "ricardo.graham@opensource.suvera.dev",
        "primary" : true
      } ],
      "displayName" : "Darren Lesch",
      "nickName" : "Nick O'Time",
      "schemas" : [ "urn:ietf:params:scim:schemas:core:2.0:User", "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User" ],
      "name" : "Delphia Reynolds",
      "externalId" : "lincoln.hintz",
      "active" : true,
      "id" : "Blanditiis",
      "userName" : "karimraz",
      "title" : "Forward Communications Planner",
      "phoneNumbers" : [ {
        "value" : "284-650-6707",
        "primary" : true
      } ],
      "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User" : {
        "division" : "Nemo sunt ",
        "costCenter" : "Quia numqu",
        "organization" : "Autem eius",
        "department" : "Earum qui ",
        "employeeNumber" : "E782831"
      }
    }

As per specification https://datatracker.ietf.org/doc/html/rfc7643#section-4.1 - it should hage a complex value. That worked in a previous version of this tool.

**Comment by suvera** [comment]
Yea, I changed the logic to generate possible data values (by their data type) for all the fields based on /Schemas  definition returned by the server.  Previously only few fields were hard coded in this test.

Please check /Schemas definition returned by server for the field User name

**Comment by gamma** [comment]
Makes sense. Here is the Schema definition for the user, returning the Type "complex" as it should be. Do you have another idea?

[user-schema.json](https://github.com/user-attachments/files/17398383/user-schema.json)

**Comment by suvera** [comment]
this is fixed in this commit https://github.com/suvera/scim2-compliance-test-utility/commit/573c73760b2f59bd22ad6c856200e8757bb86d7d
